Add EMP table

diff --git a/backend/backend/Dockerfile b/backend/backend/Dockerfile
--- a/backend/backend/Dockerfile
+++ b/backend/backend/Dockerfile
@@ -2,12 +2,10 @@
 FROM maven:3.9.6-eclipse-temurin-21 AS build
 WORKDIR /app
 COPY . .
-RUN ls -l /app && ls -l /app/.mvn/wrapper/
-RUN echo "MAVEN_CONFIG=$MAVEN_CONFIG"
-RUN ls -l /root && file /root/.m2 || echo "/root/.m2 does not exist"
-RUN ./mvnw -version
-RUN echo "MAVEN_CONFIG=$MAVEN_CONFIG" && echo "MAVEN_OPTS=$MAVEN_OPTS" && cat .mvn/maven.config || echo "no .mvn/maven.config"
-RUN MAVEN_CONFIG="" ./mvnw --no-transfer-progress package -DskipTests
+RUN chmod +x mvnw
+RUN MAVEN_CONFIG="" ./mvnw --no-transfer-progress package -DskipTests -Dquarkus.package.type=uber-jar
+RUN ls -lh /app/target
+RUN jar tf /app/target/*-runner.jar | grep create_emp_table.sql || echo "SQL SCRIPT NOT FOUND IN JAR"
 
 # Run stage
 FROM eclipse-temurin:21-jre-alpine
